'use client';

import { useEffect, useState, useCallback } from 'react';

/**
 * Browser fingerprint data
 */
export interface FingerprintData {
  /** Unique visitor ID generated by FingerprintJS */
  visitorId: string;
  /** Confidence score (0-1) */
  confidence: number;
  /** Whether fingerprinting was successful */
  success: boolean;
  /** Error message if fingerprinting failed */
  error?: string;
}

/**
 * Custom hook for generating advanced browser fingerprints using FingerprintJS.
 *
 * Uses FingerprintJS library to create a unique visitor ID based on dozens of
 * browser and device characteristics. This fingerprint persists across sessions
 * and can identify users even after clearing cookies or using private browsing.
 *
 * The fingerprint includes:
 * - Canvas rendering fingerprint
 * - WebGL rendering capabilities
 * - Audio context properties
 * - Installed system fonts
 * - Hardware concurrency (CPU cores)
 * - Device memory
 * - Screen resolution and color depth
 * - Timezone and language settings
 * - Browser plugins and features
 * - And 40+ other signals
 *
 * Headless browsers and bots typically have distinctive fingerprints that differ
 * from real browsers, making this useful for bot detection.
 *
 * @returns Object containing:
 *   - fingerprint: FingerprintData with visitorId, confidence score, and success status
 *   - isLoading: Boolean indicating if fingerprinting is in progress
 *   - getFingerprintSpamScore: Function returning spam score based on fingerprint quality
 *
 * @sideEffects
 * - Dynamically imports FingerprintJS library on mount (code splitting)
 * - Initializes FingerprintJS agent and generates fingerprint
 * - Updates state when fingerprinting completes or fails
 *
 * @example
 * ```tsx
 * const ContactForm = () => {
 *   const { fingerprint, isLoading, getFingerprintSpamScore } = useFingerprint();
 *
 *   const handleSubmit = () => {
 *     if (isLoading) {
 *       alert('Please wait...');
 *       return;
 *     }
 *
 *     const spamScore = getFingerprintSpamScore();
 *     const formData = {
 *       ...fields,
 *       visitorId: fingerprint.visitorId,
 *       spamScore
 *     };
 *
 *     // Server rejects if spamScore > threshold
 *     submitForm(formData);
 *   };
 *
 *   return <form onSubmit={handleSubmit}>...</form>;
 * };
 * ```
 *
 * @functions_called useState, useEffect, useCallback (React),
 *                    FingerprintJS.load(), fp.get() (dynamic import)
 * @called_by ContactForm, RegistrationForm, any form with advanced bot protection
 *
 * @version 1.0.0 - 2026-01-11T15:21:39Z - Initial implementation
 */
export function useFingerprint() {
  const [fingerprint, setFingerprint] = useState<FingerprintData>({
    visitorId: '',
    confidence: 0,
    success: false,
  });
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    let mounted = true;

    const getFingerprint = async () => {
      try {
        // Dynamic import to avoid SSR issues
        const FingerprintJS = await import('@fingerprintjs/fingerprintjs');

        // Initialize the agent
        const fpPromise = FingerprintJS.load();
        const fp = await fpPromise;

        // Get the visitor identifier
        const result = await fp.get();

        if (mounted) {
          setFingerprint({
            visitorId: result.visitorId,
            confidence: result.confidence.score,
            success: true,
          });
          setIsLoading(false);
        }
      } catch (error) {
        if (mounted) {
          setFingerprint({
            visitorId: '',
            confidence: 0,
            success: false,
            error: error instanceof Error ? error.message : 'Fingerprinting failed',
          });
          setIsLoading(false);
        }
      }
    };

    getFingerprint();

    return () => {
      mounted = false;
    };
  }, []);

  /**
   * Calculate spam score based on fingerprint quality and success.
   *
   * Scoring logic:
   * - Failed fingerprinting (blocked/error) = 10 points (highly suspicious)
   * - Low confidence score (< 0.5) = 5 points (moderately suspicious)
   * - Normal fingerprint with good confidence = 0 points (legitimate)
   *
   * @returns Spam score contribution (0-10 points)
   *
   * @functions_called None (reads fingerprint state)
   * @called_by Form submission handlers
   *
   * @version 1.0.0 - 2026-01-11T15:21:39Z - Initial implementation
   */
  const getFingerprintSpamScore = useCallback((): number => {
    if (!fingerprint.success) {
      return 10; // Failed fingerprinting is suspicious
    }
    if (fingerprint.confidence < 0.5) {
      return 5; // Low confidence might indicate manipulation
    }
    return 0;
  }, [fingerprint]);

  return {
    fingerprint,
    isLoading,
    getFingerprintSpamScore,
  };
}

/**
 * Generate a simple browser fingerprint for server-side validation.
 *
 * Creates a basic fingerprint by hashing browser and device characteristics.
 * This is less sophisticated than FingerprintJS but can be sent with form data
 * for additional server-side verification without requiring an external library.
 *
 * The fingerprint is created from:
 * - User agent string
 * - Browser language
 * - Screen dimensions and color depth
 * - Timezone offset
 * - Hardware concurrency (CPU cores)
 * - Device memory (if available)
 *
 * @returns Base36-encoded hash string of browser characteristics (or empty string if SSR)
 *
 * @sideEffects None - pure computation based on browser APIs
 *
 * @example
 * ```tsx
 * const handleSubmit = () => {
 *   const formData = {
 *     ...fields,
 *     fingerprint: getSimpleFingerprint()
 *   };
 *   // Server can validate fingerprint consistency
 *   submitForm(formData);
 * };
 * ```
 *
 * @functions_called navigator APIs, screen APIs, Date APIs
 * @called_by Forms requiring lightweight fingerprinting without FingerprintJS
 *
 * @version 1.0.0 - 2026-01-11T15:21:39Z - Initial implementation
 */
export function getSimpleFingerprint(): string {
  if (typeof window === 'undefined') {
    return '';
  }

  const components = [
    navigator.userAgent,
    navigator.language,
    screen.width,
    screen.height,
    screen.colorDepth,
    new Date().getTimezoneOffset(),
    navigator.hardwareConcurrency || 0,
    // @ts-expect-error - deviceMemory is not in all browsers
    navigator.deviceMemory || 0,
  ];

  // Simple hash function
  const str = components.join('|');
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    const char = str.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash = hash & hash; // Convert to 32bit integer
  }

  return Math.abs(hash).toString(36);
}
