'use client';

import { useEffect, useState, useCallback } from 'react';

/**
 * Browser fingerprint data
 */
export interface FingerprintData {
  /** Unique visitor ID generated by FingerprintJS */
  visitorId: string;
  /** Confidence score (0-1) */
  confidence: number;
  /** Whether fingerprinting was successful */
  success: boolean;
  /** Error message if fingerprinting failed */
  error?: string;
}

/**
 * Hook to generate browser fingerprint for bot detection
 *
 * Uses FingerprintJS to generate a unique visitor ID based on:
 * - Canvas fingerprint
 * - WebGL fingerprint
 * - Audio context
 * - Installed fonts
 * - Hardware concurrency
 * - Device memory
 * - Screen resolution
 * - Timezone
 * - And more...
 *
 * Headless browsers and bots typically have distinctive fingerprints
 * that can be used for detection.
 *
 * @returns Fingerprint data including visitor ID
 */
export function useFingerprint() {
  const [fingerprint, setFingerprint] = useState<FingerprintData>({
    visitorId: '',
    confidence: 0,
    success: false,
  });
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    let mounted = true;

    const getFingerprint = async () => {
      try {
        // Dynamic import to avoid SSR issues
        const FingerprintJS = await import('@fingerprintjs/fingerprintjs');

        // Initialize the agent
        const fpPromise = FingerprintJS.load();
        const fp = await fpPromise;

        // Get the visitor identifier
        const result = await fp.get();

        if (mounted) {
          setFingerprint({
            visitorId: result.visitorId,
            confidence: result.confidence.score,
            success: true,
          });
          setIsLoading(false);
        }
      } catch (error) {
        if (mounted) {
          setFingerprint({
            visitorId: '',
            confidence: 0,
            success: false,
            error: error instanceof Error ? error.message : 'Fingerprinting failed',
          });
          setIsLoading(false);
        }
      }
    };

    getFingerprint();

    return () => {
      mounted = false;
    };
  }, []);

  /**
   * Get spam score based on fingerprint
   *
   * - No fingerprint (blocked/failed) = 10 points (suspicious)
   * - Low confidence = 5 points
   * - Normal fingerprint = 0 points
   */
  const getFingerprintSpamScore = useCallback((): number => {
    if (!fingerprint.success) {
      return 10; // Failed fingerprinting is suspicious
    }
    if (fingerprint.confidence < 0.5) {
      return 5; // Low confidence might indicate manipulation
    }
    return 0;
  }, [fingerprint]);

  return {
    fingerprint,
    isLoading,
    getFingerprintSpamScore,
  };
}

/**
 * Simple fingerprint for server-side validation
 * This can be sent with form data for additional verification
 */
export function getSimpleFingerprint(): string {
  if (typeof window === 'undefined') {
    return '';
  }

  const components = [
    navigator.userAgent,
    navigator.language,
    screen.width,
    screen.height,
    screen.colorDepth,
    new Date().getTimezoneOffset(),
    navigator.hardwareConcurrency || 0,
    // @ts-expect-error - deviceMemory is not in all browsers
    navigator.deviceMemory || 0,
  ];

  // Simple hash function
  const str = components.join('|');
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    const char = str.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash = hash & hash; // Convert to 32bit integer
  }

  return Math.abs(hash).toString(36);
}
